server:
  port: 8002
spring:
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.101:3306/db2019?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  application:
    name: cloud-payment-service


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities
#eureka:
#  client:
#    service-url:
#      defaultZone:  http://localhost:8763/pancake/eureka/

eureka:
  client:
    instance:
      #为当前提供服务名称
      instance-id: payment8001
      #显示当前服务id
      prefer-ip-address: true
    #表示是否将自己注册到eureka
    register-with-eureka: true
    #是否从eureka中抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #      defaultZone:  http://localhost:7001/eureka # 单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka